name: github-actions-saludo

on:
  push:
    branches:
      - main
      - feature
      - hotfix
      - develop

jobs:
  saludo:
    runs-on: ubuntu-latest

    steps:
      - name: Saludo
        run: 
          echo "holaa buen push!!."
